// Generated by MinimIDL - C Test Harness
// DO NOT EDIT - This file was automatically generated

#include "taskmanager_wrapper.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <assert.h>

// Test result tracking
static int tests_run = 0;
static int tests_passed = 0;
static int tests_failed = 0;

#define TEST_ASSERT(condition, message) do { \
    tests_run++; \
    if (!(condition)) { \
        printf("FAIL: %s\n", message); \
        tests_failed++; \
    } else { \
        tests_passed++; \
    } \
} while(0)

#define TEST_SECTION(name) printf("\n=== Testing %s ===\n", name)

// Test Priority enum values
static void test_Priority_values() {
    TEST_SECTION("Priority Enum Values");
    
    printf("Priority_LOW = %d\n", Priority_LOW);
    printf("Priority_MEDIUM = %d\n", Priority_MEDIUM);
    printf("Priority_HIGH = %d\n", Priority_HIGH);
    printf("Priority_URGENT = %d\n", Priority_URGENT);
}

// Test Status enum values
static void test_Status_values() {
    TEST_SECTION("Status Enum Values");
    
    printf("Status_PENDING = %d\n", Status_PENDING);
    printf("Status_IN_PROGRESS = %d\n", Status_IN_PROGRESS);
    printf("Status_COMPLETED = %d\n", Status_COMPLETED);
    printf("Status_CANCELLED = %d\n", Status_CANCELLED);
}

// Test ITask interface
static void test_ITask() {
    TEST_SECTION("ITask Interface");
    
    // Create instance
    ITask_Handle obj = ITask_Create();
    if (!obj) {
        printf("WARNING: ITask_Create returned NULL - may need concrete implementation\n");
        printf("Last error: %s\n", TaskManager_GetLastError());
        return;
    }
    
    printf("Created ITask instance: %p\n", obj);
    
    // Test property: id
    {
        const char* value = ITask_Getid(obj);
        printf("id initial value: %s\n", value ? value : "(null)");
        
    }
    
    // Test property: title
    {
        const char* value = ITask_Gettitle(obj);
        printf("title initial value: %s\n", value ? value : "(null)");
        
    }
    
    // Test property: created_at
    {
        const char* value = ITask_Getcreated_at(obj);
        printf("created_at initial value: %s\n", value ? value : "(null)");
        
    }
    
    // Test property: description
    {
        const char* value = ITask_Getdescription(obj);
        printf("description initial value: %s\n", value ? value : "(null)");
        
        // Test setter
        const char* test_string = "Test String";
        ITask_Setdescription(obj, test_string);
        const char* new_value = ITask_Getdescription(obj);
        TEST_ASSERT(new_value && strcmp(new_value, test_string) == 0, "description setter should update string");
    }
    
    // Test property: priority
    
    // Test property: status
    
    // Test property: due_date
    {
        const char* value = ITask_Getdue_date(obj);
        printf("due_date initial value: %s\n", value ? value : "(null)");
        
        // Test setter
        const char* test_string = "Test String";
        ITask_Setdue_date(obj, test_string);
        const char* new_value = ITask_Getdue_date(obj);
        TEST_ASSERT(new_value && strcmp(new_value, test_string) == 0, "due_date setter should update string");
    }
    
    // Test property: tags
    {
        size_t count = ITask_Gettags_Count(obj);
        printf("tags array count: %zu\n", count);
        
        for (size_t i = 0; i < count && i < 5; i++) {
            const char* item = ITask_Gettags_Item(obj, i);
            printf("  [%zu]: %s\n", i, item ? item : "(null)");
        }
        
        // Test array modification
        ITask_Settags_Clear(obj);
        size_t new_count = ITask_Gettags_Count(obj);
        TEST_ASSERT(new_count == 0, "tags clear should empty array");
    }
    
    // Test method: Complete
    printf("\nTesting method Complete...\n");
    ITask_Complete(obj);
    printf("Complete executed\n");
    
    // Test method: Cancel
    printf("\nTesting method Cancel...\n");
    ITask_Cancel(obj);
    printf("Cancel executed\n");
    
    // Test method: IsOverdue
    printf("\nTesting method IsOverdue...\n");
    // Method has parameters or return value - would need specific test values
    printf("IsOverdue - skipping (requires test parameters)\n");
    
    // Test method: GetMetadata
    printf("\nTesting method GetMetadata...\n");
    // Method has parameters or return value - would need specific test values
    printf("GetMetadata - skipping (requires test parameters)\n");
    
    // Test method: SetMetadata
    printf("\nTesting method SetMetadata...\n");
    // Method has parameters or return value - would need specific test values
    printf("SetMetadata - skipping (requires test parameters)\n");
    
    // Cleanup
    ITask_Release(obj);
    printf("Released ITask instance\n");
}

// Test IProject interface
static void test_IProject() {
    TEST_SECTION("IProject Interface");
    
    // Create instance
    IProject_Handle obj = IProject_Create();
    if (!obj) {
        printf("WARNING: IProject_Create returned NULL - may need concrete implementation\n");
        printf("Last error: %s\n", TaskManager_GetLastError());
        return;
    }
    
    printf("Created IProject instance: %p\n", obj);
    
    // Test property: id
    {
        const char* value = IProject_Getid(obj);
        printf("id initial value: %s\n", value ? value : "(null)");
        
    }
    
    // Test property: name
    {
        const char* value = IProject_Getname(obj);
        printf("name initial value: %s\n", value ? value : "(null)");
        
        // Test setter
        const char* test_string = "Test String";
        IProject_Setname(obj, test_string);
        const char* new_value = IProject_Getname(obj);
        TEST_ASSERT(new_value && strcmp(new_value, test_string) == 0, "name setter should update string");
    }
    
    // Test property: description
    {
        const char* value = IProject_Getdescription(obj);
        printf("description initial value: %s\n", value ? value : "(null)");
        
        // Test setter
        const char* test_string = "Test String";
        IProject_Setdescription(obj, test_string);
        const char* new_value = IProject_Getdescription(obj);
        TEST_ASSERT(new_value && strcmp(new_value, test_string) == 0, "description setter should update string");
    }
    
    // Test property: active
    {
        bool value = IProject_Getactive(obj);
        printf("active initial value: ");
        printf("%s\n", value ? "true" : "false");
        
        // Test setter
        IProject_Setactive(obj, !value);
        bool new_value = IProject_Getactive(obj);
        TEST_ASSERT(new_value != value, "active setter should change value");
    }
    
    // Test method: CreateTask
    printf("\nTesting method CreateTask...\n");
    // Method has parameters or return value - would need specific test values
    printf("CreateTask - skipping (requires test parameters)\n");
    
    // Test method: GetTask
    printf("\nTesting method GetTask...\n");
    // Method has parameters or return value - would need specific test values
    printf("GetTask - skipping (requires test parameters)\n");
    
    // Test method: GetTasks
    printf("\nTesting method GetTasks...\n");
    // Method has parameters or return value - would need specific test values
    printf("GetTasks - skipping (requires test parameters)\n");
    
    // Test method: GetTasksByStatus
    printf("\nTesting method GetTasksByStatus...\n");
    // Method has parameters or return value - would need specific test values
    printf("GetTasksByStatus - skipping (requires test parameters)\n");
    
    // Test method: DeleteTask
    printf("\nTesting method DeleteTask...\n");
    // Method has parameters or return value - would need specific test values
    printf("DeleteTask - skipping (requires test parameters)\n");
    
    // Test method: GetTaskCount
    printf("\nTesting method GetTaskCount...\n");
    // Method has parameters or return value - would need specific test values
    printf("GetTaskCount - skipping (requires test parameters)\n");
    
    // Test method: GetCompletedCount
    printf("\nTesting method GetCompletedCount...\n");
    // Method has parameters or return value - would need specific test values
    printf("GetCompletedCount - skipping (requires test parameters)\n");
    
    // Test method: GetTaskCountByStatus
    printf("\nTesting method GetTaskCountByStatus...\n");
    // Method has parameters or return value - would need specific test values
    printf("GetTaskCountByStatus - skipping (requires test parameters)\n");
    
    // Cleanup
    IProject_Release(obj);
    printf("Released IProject instance\n");
}

// Test ITaskManager interface
static void test_ITaskManager() {
    TEST_SECTION("ITaskManager Interface");
    
    // Create instance
    ITaskManager_Handle obj = ITaskManager_Create();
    if (!obj) {
        printf("WARNING: ITaskManager_Create returned NULL - may need concrete implementation\n");
        printf("Last error: %s\n", TaskManager_GetLastError());
        return;
    }
    
    printf("Created ITaskManager instance: %p\n", obj);
    
    // Test method: CreateProject
    printf("\nTesting method CreateProject...\n");
    // Method has parameters or return value - would need specific test values
    printf("CreateProject - skipping (requires test parameters)\n");
    
    // Test method: GetProject
    printf("\nTesting method GetProject...\n");
    // Method has parameters or return value - would need specific test values
    printf("GetProject - skipping (requires test parameters)\n");
    
    // Test method: GetProjects
    printf("\nTesting method GetProjects...\n");
    // Method has parameters or return value - would need specific test values
    printf("GetProjects - skipping (requires test parameters)\n");
    
    // Test method: GetActiveProjects
    printf("\nTesting method GetActiveProjects...\n");
    // Method has parameters or return value - would need specific test values
    printf("GetActiveProjects - skipping (requires test parameters)\n");
    
    // Test method: DeleteProject
    printf("\nTesting method DeleteProject...\n");
    // Method has parameters or return value - would need specific test values
    printf("DeleteProject - skipping (requires test parameters)\n");
    
    // Test method: SearchTasks
    printf("\nTesting method SearchTasks...\n");
    // Method has parameters or return value - would need specific test values
    printf("SearchTasks - skipping (requires test parameters)\n");
    
    // Test method: GetTasksByPriority
    printf("\nTesting method GetTasksByPriority...\n");
    // Method has parameters or return value - would need specific test values
    printf("GetTasksByPriority - skipping (requires test parameters)\n");
    
    // Test method: GetOverdueTasks
    printf("\nTesting method GetOverdueTasks...\n");
    // Method has parameters or return value - would need specific test values
    printf("GetOverdueTasks - skipping (requires test parameters)\n");
    
    // Test method: GetSettings
    printf("\nTesting method GetSettings...\n");
    // Method has parameters or return value - would need specific test values
    printf("GetSettings - skipping (requires test parameters)\n");
    
    // Test method: UpdateSettings
    printf("\nTesting method UpdateSettings...\n");
    // Method has parameters or return value - would need specific test values
    printf("UpdateSettings - skipping (requires test parameters)\n");
    
    // Test method: Save
    printf("\nTesting method Save...\n");
    // Method has parameters or return value - would need specific test values
    printf("Save - skipping (requires test parameters)\n");
    
    // Test method: Load
    printf("\nTesting method Load...\n");
    // Method has parameters or return value - would need specific test values
    printf("Load - skipping (requires test parameters)\n");
    
    // Cleanup
    ITaskManager_Release(obj);
    printf("Released ITaskManager instance\n");
}

// Main test runner
int main(int argc, char* argv[]) {
    (void)argc;
    (void)argv;
    
    printf("=== TaskManager C Wrapper Test Suite ===\n");
    printf("Generated by MinimIDL\n");
    
    test_Priority_values();
    test_Status_values();
    
    test_ITask();
    test_IProject();
    test_ITaskManager();
    
    // Test error handling
    TEST_SECTION("Error Handling");
    TaskManager_ClearError();
    const char* error = TaskManager_GetLastError();
    TEST_ASSERT(error && strlen(error) == 0, "Error should be empty after clear");
    
    // Test with null handle
    ITask_Release(NULL);
    error = TaskManager_GetLastError();
    TEST_ASSERT(error && strstr(error, "Null handle") != NULL, "Should report null handle error");
    
    // Summary
    printf("\n=== Test Summary ===\n");
    printf("Tests run:    %d\n", tests_run);
    printf("Tests passed: %d\n", tests_passed);
    printf("Tests failed: %d\n", tests_failed);
    
    return tests_failed > 0 ? 1 : 0;
}